#!/usr/bin/env python3
"""
migrate_hermes_history.py

Migrate ~/.hermes/.hermes_history into the swiszard memory server.

The history file is a sequence of timestamped user prompts (no assistant
responses are recorded). Each substantive prompt becomes one memory with:
  - content     : the prompt itself
  - session_id  : "hermes_history_migration"
  - turn        : sequential index in the history file
  - source      : "migration"
  - tags        : ["history_migration", date]

Triggers are auto-generated by the memory server.

Filters:
  - skip prompts shorter than MIN_LEN chars
  - skip slash commands (/config, /reset, ...)
  - skip pure-greeting noise
"""
from __future__ import annotations

import json
import re
import sys
import urllib.request
from pathlib import Path

HISTORY = Path.home() / ".hermes" / ".hermes_history"
SERVER = "http://127.0.0.1:7437"

MIN_LEN = 30
NOISE = {"hi", "hello", "hey", "yo", "sup", "ok", "okay", "thanks", "ty", "cool"}
SLASH_CMD = re.compile(r"^\s*/[a-z]+")

TS_HEADER = re.compile(r"^#\s+(\d{4}-\d{2}-\d{2})\s+(\d{2}:\d{2}:\d{2})")


def parse_history(path: Path) -> list[dict]:
    """Yield {date, time, prompt} dicts from the history file."""
    entries: list[dict] = []
    current_ts: tuple[str, str] | None = None
    current_lines: list[str] = []

    def flush():
        if current_ts and current_lines:
            prompt = "\n".join(current_lines).strip()
            if prompt:
                entries.append({
                    "date":   current_ts[0],
                    "time":   current_ts[1],
                    "prompt": prompt,
                })

    for line in path.read_text(errors="replace").splitlines():
        m = TS_HEADER.match(line)
        if m:
            flush()
            current_ts = (m.group(1), m.group(2))
            current_lines = []
        elif line.startswith("+"):
            current_lines.append(line[1:])
        # ignore blank lines and other formatting

    flush()
    return entries


def is_noise(prompt: str) -> bool:
    stripped = prompt.strip()
    if len(stripped) < MIN_LEN:
        return True
    if SLASH_CMD.match(stripped):
        return True
    if stripped.lower() in NOISE:
        return True
    return False


def post_remember(content: str, turn: int, date: str) -> dict | None:
    payload = {
        "content":    content,
        "triggers":   [],            # let server auto-generate
        "kind":       "fact",
        "session_id": "hermes_history_migration",
        "turn":       turn,
        "source":     "migration",
        "tags":       ["history_migration", date],
    }
    data = json.dumps(payload).encode()
    req = urllib.request.Request(
        SERVER + "/remember", data=data,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            return json.loads(resp.read())
    except Exception as exc:
        return {"error": str(exc)}


def main() -> int:
    if not HISTORY.exists():
        print(f"ERROR: history file not found: {HISTORY}", file=sys.stderr)
        return 1

    # Probe server
    try:
        with urllib.request.urlopen(SERVER + "/health", timeout=5) as resp:
            json.loads(resp.read())
    except Exception as exc:
        print(f"ERROR: memory server not reachable at {SERVER}: {exc}", file=sys.stderr)
        return 1

    entries = parse_history(HISTORY)
    print(f"parsed {len(entries)} timestamped prompts from {HISTORY}")

    kept = [e for e in entries if not is_noise(e["prompt"])]
    skipped = len(entries) - len(kept)
    print(f"kept {len(kept)} substantive prompts ({skipped} noise filtered)")

    ok = 0
    fail = 0
    for i, e in enumerate(kept):
        # Truncate ultra-long prompts to 1200 chars to keep embeddings sharp
        content = e["prompt"][:1200]
        result = post_remember(content, turn=i, date=e["date"])
        if result and "memory_id" in result:
            ok += 1
            if ok % 25 == 0:
                print(f"  ... {ok} stored")
        else:
            fail += 1
            if fail < 5:
                print(f"  FAIL [{i}]: {result}  prompt={content[:60]!r}")

    print(f"\nDONE: stored={ok}  failed={fail}")
    return 0 if fail == 0 else 2


if __name__ == "__main__":
    sys.exit(main())
